################################################################
####         TRex nightly test configuration file          ####
################################################################

trex:
  hostname       : csi-trex-17
  cores          : 1
  modes          : [loopback, virt_nics, VM, linux_stack]
