################################################################
####         TRex nightly test configuration file          ####
################################################################


### TRex configuration:
# hostname        - can be DNS name or IP for the TRex machine for ssh to the box
# is_dual         - should the TRex inject with -p ?
# version_path    - path to the TRex version and executable
# cores           - how many cores should be used
# latency         - rate of latency packets injected by the TRex
# modes           - list of modes (tagging) of this setup (loopback, virtual etc.)
# 	  * loopback  - Trex works via loopback. Router and TFTP configurations may be skipped.
#     * VM        - Virtual OS (accept low CPU utilization in tests, latency can get spikes)
#     * virt_nics - NICs are virtual (VMXNET3 etc.)

### Router configuration:
# hostname       - the router hostname as apears in ______# cli prefix
# ip_address     - the router's ip that can be used to communicate with
# image          - the desired imaged wished to be loaded as the router's running config
# line_password  - router password when access via Telent
# en_password    - router password when changing to "enable" mode
# interfaces     - an array of client-server pairs, representing the interfaces configurations of the router
# configurations - an array of configurations that could possibly loaded into the router during the test. 
#                  The "clean" configuration is a mandatory configuration the router will load with to run the basic test bench

### TFTP configuration:
# hostname       - the tftp hostname
# ip_address     - the tftp's ip address
# images_path    - the tftp's relative path in which the router's images are located

### Test_misc configuration:
# expected_bw    - the "golden" bandwidth (in Gbps) results planned on receiving from the test

trex:
  hostname       : csi-trex-25
  cores          : 2
  modes          : ['1G']

router:
  model          : ASR1004(RP2)
  hostname       : csi-mcp-asr1k-4ru-12
  ip_address     : 10.56.217.181
  image          : asr1000rp2-adventerprisek9.BLD_V151_1_S_XE32_THROTTLE_LATEST_20100926_034325_2.bin
  line_password  : cisco
  en_password    : cisco
  mgmt_interface : GigabitEthernet0/0/0
  clean_config   : clean_config.cfg
  intf_masking   : 255.255.255.0
  ipv6_mask      : 64
  interfaces     :
    - client : 
        name          : GigabitEthernet0/1/0
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      server : 
        name          : GigabitEthernet0/1/1
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      vrf_name        : 
    - client :
        name          : GigabitEthernet0/1/2
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      server :
        name          : GigabitEthernet0/1/4
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      vrf_name        :
    - client :
        name          : GigabitEthernet0/1/5
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      server :
        name          : GigabitEthernet0/1/3
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      vrf_name        :
    - client :
        name          : GigabitEthernet0/1/6
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      server :
        name          : GigabitEthernet0/1/7
        src_mac_addr  : 0000.0001.0000
#        dest_mac_addr : 0000.0001.0000
      vrf_name      :

tftp:
  hostname       : ats-asr-srv-1
  ip_address     : 10.56.128.23
  root_dir       : /auto/avc-devtest/
  images_path    : /images/1RU/
