################################################################
####         TRex nightly test configuration file          ####
################################################################


### TRex configuration:
# hostname        - can be DNS name or IP for the TRex machine for ssh to the box
# password        - root password for TRex machine
# is_dual         - should the TRex inject with -p ?
# version_path    - path to the TRex version and executable
# cores           - how many cores should be used
# latency         - rate of latency packets injected by the TRex
# modes           - list of modes (tagging) of this setup (loopback, virtual etc.)
# 	  * loopback  - Trex works via loopback. Router and TFTP configurations may be skipped.
#     * VM        - Virtual OS (accept low CPU utilization in tests, latency can get spikes)
#     * virt_nics - NICs are virtual (VMXNET3 etc.)

### Router configuration:
# hostname       - the router hostname as apears in ______# cli prefix
# ip_address     - the router's ip that can be used to communicate with
# image          - the desired imaged wished to be loaded as the router's running config
# line_password  - router password when access via Telent
# en_password    - router password when changing to "enable" mode
# interfaces     - an array of client-server pairs, representing the interfaces configurations of the router
# configurations - an array of configurations that could possibly loaded into the router during the test. 
#                  The "clean" configuration is a mandatory configuration the router will load with to run the basic test bench

### TFTP configuration:
# hostname       - the tftp hostname
# ip_address     - the tftp's ip address
# images_path    - the tftp's relative path in which the router's images are located

### Test_misc configuration:
# expected_bw    - the "golden" bandwidth (in Gbps) results planned on receiving from the test

trex:
  hostname       : 10.56.217.210 #10.56.192.189
  cores          : 4

router:
  model          : ESP100
  hostname       : csi-mcp-asr1k-40
  ip_address     : 10.56.192.57
  image          : BLD_V155_2_S_XE315_THROTTLE_LATEST_20150424_100040-std.bin # is in harddisk of router
  #image          : asr1000rp2-adventerprisek9.2014-11-10_18.33_etis.bin
  line_password  : cisco
  en_password    : cisco
  mgmt_interface : GigabitEthernet0
  clean_config   : /tmp/asr1001_TRex_clean_config.cfg
  intf_masking   : 255.255.255.0
  ipv6_mask      : 64
  interfaces     :
    - client : 
        name          : TenGigabitEthernet0/0/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      server : 
        name          : TenGigabitEthernet0/1/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      vrf_name      :   duplicate
    - client : 
        name          : TenGigabitEthernet0/2/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      server : 
        name          : TenGigabitEthernet0/3/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      vrf_name      :   duplicate
    - client : 
        name          : TenGigabitEthernet1/0/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      server : 
        name          : TenGigabitEthernet1/1/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      vrf_name      :   
    - client : 
        name          : TenGigabitEthernet1/2/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      server : 
        name          : TenGigabitEthernet1/3/0
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      vrf_name      :   
    

tftp:
  hostname       : kiwi02_tftp_server
  ip_address     : 10.56.217.7
  root_dir       : /scratch/tftp/
  images_path    : hhaim/
